# Generated by Django 4.2.3 on 2023-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESS', 'PROCESS'), ('DELIVER', 'DELIVER')], default='PENDING', max_length=20),
        ),
    ]
