# Generated by Django 4.2.3 on 2023-09-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_addproductmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproductmodel',
            name='status',
        ),
    ]
