# Generated by Django 4.2.3 on 2023-09-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_addproductmodel_status'),
        ('review_rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewratingmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='reviewratingmodel',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.addproductmodel'),
        ),
    ]
