# Generated by Django 4.2.3 on 2023-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_order',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESS', 'PROCESS'), ('DELIVER', 'DELIVER')], default='PENDING', max_length=20),
        ),
    ]
